name = "navix-api"
main = "src/index.ts"
compatibility_date = "2024-05-01"
workers_dev = true
account_id = "72f7f49f94fd223a4d11c28588c23266"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "navix-db"
database_id = "602c8e40-01ac-4445-82ab-dfac888a5192"
preview_database_id = "602c8e40-01ac-4445-82ab-dfac888a5192"
migrations_dir = "migrations"
