-- Generated by backend/scripts/mongo-to-d1-seed.mjs
-- Source: ../data/mongodb/places.sample.json

DELETE FROM places;
INSERT INTO places (name, nearest_site, district, verified_history, cultural_rules, lat, lng) VALUES ('Sigiriya Rock Fortress', 'Sigiriya Rock Fortress', 'Matale', 'Built by King Kashyapa in the 5th century AD.', '["No graffiti","Moderate climbing stamina required"]', 7.957, 80.7603);
